name: Test
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install chromium
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 297097 # Chromium 39.0.2171.99 (Android - 5.1.0)
      - name: Run tests
        shell: bash
        env:
          CHROMIUM_BIN: ${{which chrome}}
        run: |
          yarn install --frozen-lockfile
          yarn run ci:test
      - name: Coveralls
        if: ${{ matrix.node-version == '18.x' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        shell: bash
        run: |
          yarn add coveralls -D
          yarn run coveralls
