name: Test
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install chromium dependencies
        if: ${{ matrix.node-version == '18.x' }}
        run: |
          sudo apt install libudev-dev libgtk2.0-0
          sudo ln -sf /lib/$(arch)-linux-gnu/libudev.so.1 /lib/$(arch)-linux-gnu/libudev.so.0

      - name: Install chromium
        if: ${{ matrix.node-version == '18.x' }}
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 297097 # Chromium 39.0.2171.99 (Android - 5.1.0)

      - name: Install chromium sandbox
        if: ${{ matrix.node-version == '18.x' }}
        run: |
          sudo cp /opt/hostedtoolcache/chromium/297097/x64/chrome_sandbox /usr/local/sbin/chrome-devel-sandbox
          sudo chown root:root /usr/local/sbin/chrome-devel-sandbox
          sudo chmod 4755 /usr/local/sbin/chrome-devel-sandbox
          sudo xhost +

      - name: Install node modules and build
        run: |
          yarn install --frozen-lockfile
          yarn run build

      - name: Karma tests
        if: ${{ matrix.node-version == '18.x' }}
        env:
          CHROMIUM_BIN: /opt/hostedtoolcache/chromium/297097/x64/chrome
          CHROME_DEVEL_SANDBOX: /usr/local/sbin/chrome-devel-sandbox
        run: |
          export DISPLAY=:99.0
          yarn run test:karma

      - name: Mocha tests
        shell: bash
        run: |
          yarn run test:mocha:ci

      - name: Coveralls
        if: ${{ matrix.node-version == '18.x' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        shell: bash
        run: |
          yarn add coveralls -D
          yarn run coveralls
